#!/usr/bin/env python3
"""Generate repetitive MBAA Pipeline and ProjectInterface resources."""

from __future__ import annotations

import argparse
import json
import sys
from collections import OrderedDict
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent.parent
SPEC_PATH = ROOT / "tools" / "resource_specs" / "resources.json"
GENERATED_HEADER = "// AUTO-GENERATED by tools/generate_resources.py. DO NOT EDIT.\n"


def node_name(category: dict[str, Any], stem: str, suffix: str) -> str:
    return f"{stem}{category['prefix']}{suffix}"


def remaining_routes(spec: dict[str, Any], index: int) -> list[str]:
    suffix = spec["flow_suffix"]
    routes = [
        node_name(category, "Run", suffix)
        for category in spec["categories"][index + 1 :]
    ]
    routes.append(spec["return_node"])
    return routes


def generate_sweep(spec: dict[str, Any]) -> OrderedDict[str, Any]:
    out: OrderedDict[str, Any] = OrderedDict()
    root = spec["root"]
    suffix = spec["flow_suffix"]
    categories = spec["categories"]

    out[spec["entry"]] = {
        "timeout": 10000,
        "rate_limit": 250,
        "next": ["[JumpBack]NavOpenTasks", "[JumpBack]NavLoading", spec["jump_node"]],
    }
    out[spec["jump_node"]] = {
        "recognition": "TemplateMatch",
        "template": spec["task_template"],
        "threshold": 0.7,
        "action": "Click",
        "max_hit": 3,
        "post_wait_freezes": 500,
        "next": ["[JumpBack]NavLoading", spec["jump_node"], spec["plan"]],
        "timeout": 1200,
        "rate_limit": 150,
        "roi": spec["task_roi"],
    }
    out[spec["plan"]] = {
        "next": [node_name(category, "Run", suffix) for category in categories]
        + [spec["return_node"]]
    }

    for index, category in enumerate(categories):
        prefix = category["prefix"]
        routes = remaining_routes(spec, index)
        run = node_name(category, "Run", suffix)
        open_category = node_name(category, "Open", f"{suffix}Category")
        find_stage = node_name(category, "Find", f"{suffix}Stage")
        find_number = node_name(category, "Find", f"{suffix}StageNumber")
        scroll = node_name(category, "Scroll", f"{suffix}StageListDown")
        wait_info = node_name(category, "Wait", "SweepInfo")
        add_count = node_name(category, "Add", "SweepCount")
        start = node_name(category, "Start", "Sweep")
        confirm_start = node_name(category, "Confirm", "SweepStart")
        wait_start_closed = node_name(category, "Wait", "SweepStartConfirmClosed")
        retry_start = node_name(category, "RetryConfirm", "SweepStart")
        confirm_complete = node_name(category, "Confirm", "SweepComplete")
        wait_complete_closed = node_name(category, "Wait", "SweepCompleteClosed")
        retry_complete = node_name(category, "RetryConfirm", "SweepComplete")
        close_info = node_name(category, "Close", f"{suffix}Info")
        wait_info_closed = node_name(category, "Wait", f"{suffix}InfoClosed")
        retry_info = node_name(category, "RetryClose", f"{suffix}Info")
        return_category = node_name(category, "Return", f"{suffix}ListToCategory")

        out[run] = {
            "enabled": False,
            "timeout": 3000,
            "next": [open_category],
            "on_error": routes,
        }
        out[open_category] = {
            "recognition": "TemplateMatch",
            "template": category["template"],
            "threshold": 0.7,
            "action": "Click",
            "post_wait_freezes": 500,
            "next": [find_stage],
            "timeout": 1500,
            "roi": category["roi"],
        }
        out[find_stage] = {
            "timeout": 2000,
            "next": [find_number, scroll],
            "on_error": [return_category],
        }
        out[find_number] = {
            "recognition": "OCR",
            "roi": [695, 130, 65, 545],
            "expected": f"^{spec['default_stage']:02d}$",
            "replace": [["O", "0"], ["o", "0"]],
            "threshold": 0.3,
            "action": "Click",
            "target": True,
            "target_offset": [355, -9, 75, 35],
            "post_wait_freezes": 500,
            "next": [wait_info],
        }
        out[scroll] = {
            "max_hit": spec["max_scroll"],
            "action": "Swipe",
            "begin": [960, 650],
            "end": [960, 250],
            "duration": 500,
            "post_wait_freezes": 500,
            "next": [find_stage],
        }
        out[wait_info] = {
            "recognition": "TemplateMatch",
            "template": "common/sweep_start.png",
            "threshold": 0.8,
            "timeout": 3000,
            "next": [add_count, start],
            "roi": [700, 335, 470, 130],
        }
        out[add_count] = {
            "enabled": False,
            "recognition": "TemplateMatch",
            "template": "common/sweep_plus.png",
            "threshold": 0.8,
            "action": "Click",
            "repeat": 1,
            "repeat_delay": 150,
            "post_wait_freezes": 300,
            "next": [start],
            "roi": [950, 235, 130, 120],
        }
        out[start] = {
            "recognition": "TemplateMatch",
            "template": "common/sweep_start.png",
            "threshold": 0.8,
            "action": "Click",
            "post_wait_freezes": 500,
            "timeout": 3000,
            "next": [confirm_start],
            "on_error": [close_info],
            "roi": [700, 335, 470, 130],
        }
        out[confirm_start] = {
            "recognition": "TemplateMatch",
            "template": "common/sweep_start_confirm.png",
            "threshold": 0.8,
            "action": "Click",
            "post_wait_freezes": 500,
            "timeout": 3000,
            "next": [wait_start_closed],
            "on_error": [close_info],
            "roi": [600, 430, 340, 140],
        }
        out[wait_start_closed] = {
            "recognition": "TemplateMatch",
            "template": "common/sweep_start_confirm.png",
            "threshold": 0.8,
            "inverse": True,
            "timeout": 1200,
            "next": [confirm_complete],
            "on_error": [retry_start],
            "roi": [600, 430, 340, 140],
        }
        out[retry_start] = {
            "recognition": "TemplateMatch",
            "template": "common/sweep_start_confirm.png",
            "threshold": 0.8,
            "action": "Click",
            "post_wait_freezes": 500,
            "timeout": 1500,
            "next": [wait_start_closed],
            "on_error": [close_info],
            "roi": [600, 430, 340, 140],
        }
        out[confirm_complete] = {
            "recognition": "TemplateMatch",
            "template": "common/sweep_complete_final.png",
            "threshold": 0.8,
            "action": "Click",
            "target": [545, 555, 190, 50],
            "post_wait_freezes": 800,
            "timeout": 30000,
            "next": [wait_complete_closed],
            "roi": [160, 410, 950, 130],
        }
        out[wait_complete_closed] = {
            "recognition": "TemplateMatch",
            "template": "common/sweep_complete_final.png",
            "threshold": 0.8,
            "inverse": True,
            "timeout": 1200,
            "next": [close_info],
            "on_error": [retry_complete],
            "roi": [160, 410, 950, 130],
        }
        out[retry_complete] = {
            "recognition": "TemplateMatch",
            "template": "common/sweep_complete_final.png",
            "threshold": 0.8,
            "action": "Click",
            "target": [545, 555, 190, 50],
            "post_wait_freezes": 800,
            "timeout": 1500,
            "next": [wait_complete_closed],
            "on_error": [close_info],
            "roi": [160, 410, 950, 130],
        }
        out[close_info] = {
            "recognition": "TemplateMatch",
            "template": "common/sweep_info_close.png",
            "threshold": 0.8,
            "action": "Click",
            "post_wait_freezes": 500,
            "next": [wait_info_closed],
            "timeout": 2000,
            "roi": [1040, 50, 150, 140],
        }
        out[wait_info_closed] = {
            "recognition": "TemplateMatch",
            "template": "common/sweep_info_close.png",
            "threshold": 0.8,
            "inverse": True,
            "timeout": 1000,
            "next": [return_category],
            "on_error": [retry_info],
            "roi": [1040, 50, 150, 140],
        }
        out[retry_info] = {
            "recognition": "TemplateMatch",
            "template": "common/sweep_info_close.png",
            "threshold": 0.8,
            "action": "Click",
            "post_wait_freezes": 500,
            "timeout": 1500,
            "next": [wait_info_closed],
            "on_error": [return_category],
            "roi": [1040, 50, 150, 140],
        }
        out[return_category] = {
            "action": "Click",
            "target": [56, 37],
            "post_wait_freezes": 500,
            "next": routes,
            "timeout": 3000,
        }

    out[spec["return_node"]] = {
        "action": "Click",
        "target": [56, 37],
        "post_wait_freezes": 500,
        "timeout": 3000,
        "next": [spec["returned_node"]],
        "on_error": ["NavReturnToMain"],
    }
    out[spec["returned_node"]] = {
        "recognition": "TemplateMatch",
        "template": spec["task_template"],
        "threshold": 0.7,
        "next": ["NavReturnToMain"],
        "roi": spec["task_roi"],
    }
    return out


def shop_page_routes(spec: dict[str, Any], index: int, page: int) -> list[str]:
    category = spec["categories"][index]
    pages = (category["rows"] + 1) // 2
    if page < pages:
        return [f"Scroll{category['prefix']}ShopGoodsToPage{page + 1}"]
    routes = [
        f"Run{category['prefix']}ShopPurchase"
        for category in spec["categories"][index + 1 :]
    ]
    routes.append("ReturnShopToMain")
    return routes


def add_shop_page(
    out: OrderedDict[str, Any], spec: dict[str, Any], category: dict[str, Any], index: int, page: int
) -> None:
    prefix = category["prefix"]
    page_prefix = f"{prefix}ShopPage{page}"
    first_row = (page - 1) * 2 + 1
    item_count = 8
    after = f"{page_prefix}AfterItems"
    continuation = shop_page_routes(spec, index, page)

    for item in range(1, item_count + 1):
        local_row = (item - 1) // 4
        column = (item - 1) % 4 + 1
        row = first_row + local_row
        gate = f"{page_prefix}Item{item}"
        click = f"Click{prefix}ShopItemR{row}C{column}"
        next_gate = f"{page_prefix}Item{item + 1}" if item < item_count else after
        out[gate] = {"next": [click, next_gate]}
        out[click] = {
            "enabled": False,
            "action": "Click",
            "target": [spec["columns"][column - 1], spec["visible_rows"][local_row]],
            "post_wait_freezes": 200,
            "next": [next_gate],
        }

    purchase = f"Purchase{prefix}ShopPage{page}"
    confirm = f"Confirm{prefix}ShopPurchasePage{page}"
    wait_confirm = f"Wait{prefix}ShopPurchaseConfirmPage{page}Closed"
    retry_confirm = f"RetryConfirm{prefix}ShopPurchasePage{page}"
    cancel = f"Cancel{prefix}ShopPurchasePage{page}"
    wait_reward = f"Wait{prefix}ShopPurchaseRewardPage{page}"
    wait_success = f"Wait{prefix}ShopPurchaseSuccessPage{page}"
    wait_success_closed = f"Wait{prefix}ShopPurchaseSuccessPage{page}Closed"
    retry_success = f"RetryClose{prefix}ShopPurchaseSuccessPage{page}"

    out[after] = {"next": [purchase, *continuation]}
    out[purchase] = {
        "enabled": False,
        "recognition": "TemplateMatch",
        "template": "shop/select_purchase.png",
        "threshold": 0.8,
        "action": "Click",
        "post_wait_freezes": 500,
        "timeout": 2000,
        "next": [confirm],
        "on_error": continuation,
        "roi": [1000, 580, 280, 140],
    }
    out[confirm] = {
        "recognition": "TemplateMatch",
        "template": "shop/purchase_confirm.png",
        "threshold": 0.8,
        "action": "Click",
        "post_wait_freezes": 500,
        "timeout": 3000,
        "next": [wait_confirm],
        "on_error": [cancel],
        "roi": [600, 450, 340, 170],
    }
    out[wait_confirm] = {
        "recognition": "TemplateMatch",
        "template": "shop/purchase_confirm.png",
        "threshold": 0.8,
        "inverse": True,
        "timeout": spec["reward_page_open_timeout"],
        "next": [wait_reward],
        "on_error": [retry_confirm],
        "roi": [600, 450, 340, 170],
    }
    out[retry_confirm] = {
        "recognition": "TemplateMatch",
        "template": "shop/purchase_confirm.png",
        "threshold": 0.8,
        "action": "Click",
        "post_wait_freezes": 500,
        "timeout": 1500,
        "next": [wait_confirm],
        "on_error": [cancel],
        "roi": [600, 450, 340, 170],
    }
    out[cancel] = {
        "action": "Click",
        "target": [514, 575],
        "post_wait_freezes": 500,
        "next": continuation,
    }
    out[wait_reward] = {
        "recognition": "TemplateMatch",
        "template": "common/reward_success.png",
        "roi": [430, 95, 450, 170],
        "threshold": 0.7,
        "timeout": spec["reward_animation_timeout"],
        "rate_limit": 250,
        "next": [wait_success],
        "on_error": [retry_success],
    }
    out[wait_success] = {
        "recognition": "TemplateMatch",
        "template": "common/reward_continue.png",
        "roi": [480, 590, 330, 80],
        "threshold": 0.75,
        "action": "Click",
        "target": [640, 632],
        "post_wait_freezes": 800,
        "timeout": 3000,
        "next": [wait_success_closed],
        "on_error": [retry_success],
    }
    out[wait_success_closed] = {
        "recognition": "TemplateMatch",
        "template": "common/reward_success.png",
        "roi": [430, 95, 450, 170],
        "threshold": 0.7,
        "inverse": True,
        "next": continuation,
    }
    out[retry_success] = {
        "max_hit": 5,
        "action": "Click",
        "target": [640, 632],
        "post_wait_freezes": 800,
        "timeout": 2000,
        "next": [wait_success_closed],
        "on_error": [retry_success],
    }

    pages = (category["rows"] + 1) // 2
    if page < pages:
        scroll = spec["goods_scroll"]
        out[continuation[0]] = {
            "action": "Swipe",
            "begin": scroll["begin"],
            "end": scroll["end"],
            "duration": scroll["duration"],
            "post_wait_freezes": 500,
            "next": [f"{prefix}ShopPage{page + 1}Item1"],
        }


def generate_shop(spec: dict[str, Any]) -> OrderedDict[str, Any]:
    out: OrderedDict[str, Any] = OrderedDict()
    categories = spec["categories"]
    out[spec["entry"]] = {
        "timeout": 8000,
        "rate_limit": 250,
        "next": ["[JumpBack]NavOpenShop", "[JumpBack]NavLoading", "WaitShopOpened"],
        "on_error": ["ReturnShopToMain"],
    }
    out["WaitShopOpened"] = {
        "recognition": "TemplateMatch",
        "template": "shop/general_tab.png",
        "threshold": 0.7,
        "timeout": 1500,
        "next": ["RunShopPurchasePlan"],
        "roi": [0, 90, 300, 150],
    }
    out["RunShopPurchasePlan"] = {
        "next": [f"Run{category['prefix']}ShopPurchase" for category in categories]
        + ["ReturnShopToMain"]
    }

    for index, category in enumerate(categories):
        prefix = category["prefix"]
        next_routes = [f"Run{c['prefix']}ShopPurchase" for c in categories[index + 1 :]]
        next_routes.append("ReturnShopToMain")
        run = f"Run{prefix}ShopPurchase"
        first_item = f"{prefix}ShopPage1Item1"
        open_spec = category["open"]
        if open_spec["type"] == "coordinate":
            open_node = f"Open{prefix}ShopCategory"
            out[run] = {
                "enabled": False,
                "timeout": 3000,
                "next": [open_node],
                "on_error": next_routes,
            }
            out[open_node] = {
                "action": "Click",
                "target": open_spec["target"],
                "post_wait_freezes": 500,
                "next": [first_item],
                "timeout": 1500,
            }
        else:
            scroll = f"ScrollShopCategoryListTo{prefix}"
            open_node = f"Open{prefix}ShopCategory"
            fallback = f"Open{prefix}ShopCategoryByCoordinate"
            out[run] = {
                "enabled": False,
                "timeout": 3000,
                "next": [scroll],
                "on_error": next_routes,
            }
            out[scroll] = {
                "action": "Swipe",
                "begin": [120, 560],
                "end": [120, 185],
                "duration": 500,
                "post_wait_freezes": 500,
                "next": [open_node],
            }
            out[open_node] = {
                "recognition": "TemplateMatch",
                "template": open_spec["template"],
                "roi": open_spec["roi"],
                "threshold": 0.7,
                "action": "Click",
                "post_wait_freezes": 500,
                "next": [first_item],
                "on_error": [fallback],
                "timeout": 1500,
            }
            out[fallback] = {
                "action": "Click",
                "target": open_spec["fallback_target"],
                "post_wait_freezes": 500,
                "next": [first_item],
                "timeout": 1500,
            }

        for page in range(1, (category["rows"] + 1) // 2 + 1):
            add_shop_page(out, spec, category, index, page)

    out["ReturnShopToMain"] = {"next": ["NavReturnToMain"]}
    return out


def schedule_candidate_gate(round_prefix: str, index: int) -> str:
    return f"{round_prefix}ScheduleCandidate{index}Plan"


def add_schedule_candidate(
    out: OrderedDict[str, Any],
    spec: dict[str, Any],
    round_prefix: str,
    candidate_kind: str,
    index: int,
    candidate_count: int,
    finish_node: str,
) -> None:
    templates = spec["templates"]
    roi = spec["roi"]
    prefix = f"{round_prefix}ScheduleCandidate{index}"
    gate = schedule_candidate_gate(round_prefix, index)
    next_gate = (
        schedule_candidate_gate(round_prefix, index + 1)
        if index + 1 < candidate_count
        else finish_node
    )
    find = f"Find{prefix}"
    verify_heart = f"Verify{prefix}Heart"
    verify_available = f"Verify{prefix}NotCompleted"
    wait_info = f"Wait{prefix}InfoOpened"
    retry_open = f"RetryOpen{prefix}Info"
    click_start = f"Start{prefix}Lesson"
    retry_start1 = f"RetryStart{prefix}Lesson1"
    retry_start2 = f"RetryStart{prefix}Lesson2"
    report_visible = f"Wait{prefix}Report"
    confirm_report = f"Confirm{prefix}Report"
    wait_report_closed = f"Wait{prefix}ReportClosed"
    retry_report1 = f"RetryConfirm{prefix}Report1"
    retry_report2 = f"RetryConfirm{prefix}Report2"
    close_bond = f"Close{prefix}BondLevelUp"
    wait_bond_closed = f"Wait{prefix}BondLevelUpClosed"
    retry_bond1 = f"RetryClose{prefix}BondLevelUp1"
    retry_bond2 = f"RetryClose{prefix}BondLevelUp2"
    wait_after_report = f"Wait{prefix}AllScheduleAfterReport"
    close_info = f"Close{prefix}UnavailableInfo"
    wait_info_closed = f"Wait{prefix}InfoClosed"
    retry_close_info = f"RetryClose{prefix}Info"
    wait_after_info = f"Wait{prefix}AllScheduleAfterInfo"

    out[gate] = {
        "timeout": 1000,
        "next": ["ScheduleTicketsEmpty", find, finish_node],
        "on_error": ["RecoverScheduleToMain"],
    }

    if candidate_kind == "special":
        out[find] = {
            "recognition": "FeatureMatch",
            "template": spec["special_student_dir"],
            "roi": roi["students"],
            "count": 5,
            "ratio": 0.72,
            "detector": "SIFT",
            "order_by": "Vertical",
            "index": index,
            "timeout": 800,
            "next": [verify_heart],
            "on_error": [next_gate],
        }
        out[verify_heart] = {
            "recognition": "TemplateMatch",
            "template": templates["heart"],
            "roi": find,
            "roi_offset": [-8, -8, 35, 35],
            "threshold": spec["special_heart_threshold"],
            "green_mask": True,
            "timeout": 800,
            "next": [verify_available],
            "on_error": [next_gate],
        }
        completed_roi = find
        completed_offset = [-8, -8, 35, 35]
        click_target = find
        click_offset = None
    else:
        out[find] = {
            "recognition": "TemplateMatch",
            "template": templates["heart"],
            "roi": roi["students"],
            "threshold": spec["heart_threshold"],
            "green_mask": True,
            "order_by": "Vertical",
            "index": index,
            "timeout": 800,
            "next": [verify_available],
            "on_error": [next_gate],
        }
        completed_roi = find
        completed_offset = [-5, -42, 12, 45]
        click_target = find
        click_offset = [-34, -18, 0, 0]

    verify_node: dict[str, Any] = {
        "recognition": "TemplateMatch",
        "template": templates["completed_check"],
        "roi": completed_roi,
        "roi_offset": completed_offset,
        "threshold": 0.65,
        "green_mask": True,
        "inverse": True,
        "action": "Click",
        "target": click_target,
        "post_wait_freezes": 300,
        "timeout": 3000,
        "next": [wait_info],
        "on_error": [retry_open],
    }
    if click_offset is not None:
        verify_node["target_offset"] = click_offset
    out[verify_available] = verify_node

    out[retry_open] = {
        "action": "Click",
        "target": click_target,
        "post_wait_freezes": 300,
        "timeout": 3000,
        "next": [wait_info],
        "on_error": [close_info],
    }
    if click_offset is not None:
        out[retry_open]["target_offset"] = click_offset

    out[wait_info] = {
        "recognition": "TemplateMatch",
        "template": templates["info_title"],
        "roi": roi["info_title"],
        "threshold": 0.75,
        "timeout": 3000,
        "next": [click_start],
        "on_error": [close_info],
    }
    out[click_start] = {
        "recognition": "TemplateMatch",
        "template": templates["start_button"],
        "roi": roi["start_button"],
        "threshold": 0.75,
        "action": "Click",
        "post_wait_freezes": 500,
        "timeout": 10000,
        "next": [close_bond, report_visible, "[JumpBack]NavLoading", retry_start1],
        "on_error": ["RecoverScheduleToMain"],
    }
    out[retry_start1] = {
        "recognition": "TemplateMatch",
        "template": templates["start_button"],
        "roi": roi["start_button"],
        "threshold": 0.75,
        "action": "Click",
        "post_wait_freezes": 500,
        "timeout": 10000,
        "next": [close_bond, report_visible, "[JumpBack]NavLoading", retry_start2],
        "on_error": ["RecoverScheduleToMain"],
    }
    out[retry_start2] = {
        "recognition": "TemplateMatch",
        "template": templates["start_button"],
        "roi": roi["start_button"],
        "threshold": 0.75,
        "action": "Click",
        "post_wait_freezes": 500,
        "timeout": 10000,
        "next": [close_bond, report_visible, "[JumpBack]NavLoading"],
        "on_error": ["RecoverScheduleToMain"],
    }
    out[report_visible] = {
        "recognition": "TemplateMatch",
        "template": templates["report_title"],
        "roi": roi["report_title"],
        "threshold": 0.75,
        "timeout": 15000,
        "next": [confirm_report],
        "on_error": ["RecoverScheduleToMain"],
    }
    out[confirm_report] = {
        "recognition": "TemplateMatch",
        "template": templates["report_confirm"],
        "roi": roi["report_confirm"],
        "threshold": 0.75,
        "action": "Click",
        "post_wait_freezes": 700,
        "timeout": 2500,
        "next": [wait_report_closed],
        "on_error": [retry_report1],
    }
    out[wait_report_closed] = {
        "recognition": "TemplateMatch",
        "template": templates["report_title"],
        "roi": roi["report_title"],
        "threshold": 0.75,
        "inverse": True,
        "timeout": 3000,
        "next": [wait_after_report],
        "on_error": ["RecoverScheduleToMain"],
    }
    out[retry_report1] = {
        "action": "Click",
        "target": [640, 555],
        "post_wait_freezes": 700,
        "timeout": 2500,
        "next": [wait_report_closed],
        "on_error": [retry_report2],
    }
    out[retry_report2] = {
        "action": "Click",
        "target": [640, 555],
        "post_wait_freezes": 700,
        "timeout": 2500,
        "next": [wait_report_closed],
        "on_error": ["RecoverScheduleToMain"],
    }
    out[close_bond] = {
        "recognition": "TemplateMatch",
        "template": templates["bond_level_up_title"],
        "roi": roi["bond_level_up_title"],
        "threshold": 0.7,
        "action": "Click",
        "target": [640, 650],
        "post_delay": 500,
        "timeout": 1200,
        "next": [wait_bond_closed],
        "on_error": [retry_bond1],
    }
    out[wait_bond_closed] = {
        "recognition": "TemplateMatch",
        "template": templates["bond_level_up_title"],
        "roi": roi["bond_level_up_title"],
        "threshold": 0.7,
        "inverse": True,
        "timeout": 15000,
        "rate_limit": 200,
        "next": [report_visible, "[JumpBack]NavLoading"],
        "on_error": ["RecoverScheduleToMain"],
    }
    out[retry_bond1] = {
        "action": "Click",
        "target": [640, 650],
        "post_delay": 500,
        "timeout": 1200,
        "next": [wait_bond_closed],
        "on_error": [retry_bond2],
    }
    out[retry_bond2] = {
        "action": "Click",
        "target": [640, 650],
        "post_delay": 500,
        "timeout": 1200,
        "next": [wait_bond_closed],
        "on_error": ["RecoverScheduleToMain"],
    }
    out[wait_after_report] = {
        "recognition": "TemplateMatch",
        "template": templates["all_schedule_title"],
        "roi": roi["all_schedule_title"],
        "threshold": 0.75,
        "next": [next_gate],
    }

    out[close_info] = {
        "action": "Click",
        "target": [964, 114],
        "post_wait_freezes": 300,
        "timeout": 2000,
        "next": [wait_info_closed],
        "on_error": [retry_close_info],
    }
    out[wait_info_closed] = {
        "recognition": "TemplateMatch",
        "template": templates["info_title"],
        "roi": roi["info_title"],
        "threshold": 0.75,
        "inverse": True,
        "timeout": 2500,
        "next": [wait_after_info],
        "on_error": ["RecoverScheduleToMain"],
    }
    out[retry_close_info] = {
        "action": "Click",
        "target": [964, 114],
        "post_wait_freezes": 300,
        "timeout": 2000,
        "next": [wait_info_closed],
        "on_error": ["RecoverScheduleToMain"],
    }
    out[wait_after_info] = {
        "recognition": "TemplateMatch",
        "template": templates["all_schedule_title"],
        "roi": roi["all_schedule_title"],
        "threshold": 0.75,
        "next": [next_gate],
    }


def generate_schedule(spec: dict[str, Any]) -> OrderedDict[str, Any]:
    out: OrderedDict[str, Any] = OrderedDict()
    templates = spec["templates"]
    roi = spec["roi"]
    first_gate = schedule_candidate_gate("FirstRound", 0)
    second_gate = schedule_candidate_gate("SecondRound", 0)

    out[spec["entry"]] = {
        "timeout": 10000,
        "rate_limit": 250,
        "next": [
            "[JumpBack]NavOpenSchedule",
            "[JumpBack]NavLoading",
            "WaitScheduleHomeOpened",
        ],
        "on_error": ["RecoverScheduleToMain"],
    }
    out["WaitScheduleHomeOpened"] = {
        "recognition": "TemplateMatch",
        "template": templates["home_title"],
        "roi": roi["home_title"],
        "threshold": 0.75,
        "timeout": 3000,
        "next": ["ScheduleHomeTicketsEmpty", "OpenScheduleFirstRegionFirstRound"],
        "on_error": ["RecoverScheduleToMain"],
    }
    out["ScheduleHomeTicketsEmpty"] = {
        "recognition": "OCR",
        "roi": roi["home_tickets"],
        "expected": spec["ticket_empty_expected"],
        "replace": [["O", "0"], ["o", "0"], [" ", ""]],
        "threshold": 0.3,
        "next": ["NavReturnToMain"],
    }
    out["ScheduleTicketsEmpty"] = {
        "recognition": "OCR",
        "roi": roi["all_schedule_tickets"],
        "expected": spec["ticket_empty_expected"],
        "replace": [["O", "0"], ["o", "0"], [" ", ""]],
        "threshold": 0.3,
        "next": ["CloseScheduleAllForNoTickets"],
    }

    for round_prefix, open_first, wait_first, open_all, wait_all, run_region in (
        (
            "FirstRound",
            "OpenScheduleFirstRegionFirstRound",
            "WaitScheduleFirstRegionFirstRound",
            "OpenScheduleFirstRoundAllSchedule",
            "WaitScheduleFirstRoundAllScheduleOpened",
            "RunScheduleFirstRoundRegion",
        ),
        (
            "SecondRound",
            "OpenScheduleFirstRegionSecondRound",
            "WaitScheduleFirstRegionSecondRound",
            "OpenScheduleSecondRoundAllSchedule",
            "WaitScheduleSecondRoundAllScheduleOpened",
            "RunScheduleSecondRoundRegion",
        ),
    ):
        retry_first = f"Retry{open_first}"
        retry_all = f"Retry{open_all}"
        gate = first_gate if round_prefix == "FirstRound" else second_gate
        out[open_first] = {
            "recognition": "TemplateMatch",
            "template": templates["first_region_card"],
            "roi": roi["first_region_card"],
            "threshold": 0.75,
            "action": "Click",
            "post_wait_freezes": 500,
            "timeout": 5000,
            "next": [wait_first, "[JumpBack]NavLoading", retry_first],
            "on_error": ["RecoverScheduleToMain"],
        }
        out[retry_first] = {
            "recognition": "TemplateMatch",
            "template": templates["first_region_card"],
            "roi": roi["first_region_card"],
            "threshold": 0.75,
            "action": "Click",
            "post_wait_freezes": 500,
            "timeout": 5000,
            "next": [wait_first, "[JumpBack]NavLoading"],
            "on_error": ["RecoverScheduleToMain"],
        }
        out[wait_first] = {
            "recognition": "TemplateMatch",
            "template": templates["first_region_title"],
            "roi": roi["region_name"],
            "threshold": 0.75,
            "timeout": 5000,
            "next": [open_all],
            "on_error": ["RecoverScheduleToMain"],
        }
        out[open_all] = {
            "recognition": "TemplateMatch",
            "template": templates["all_schedule_button"],
            "roi": roi["all_schedule_button"],
            "threshold": 0.75,
            "action": "Click",
            "post_wait_freezes": 500,
            "timeout": 5000,
            "next": [wait_all, "[JumpBack]NavLoading", retry_all],
            "on_error": ["RecoverScheduleToMain"],
        }
        out[retry_all] = {
            "recognition": "TemplateMatch",
            "template": templates["all_schedule_button"],
            "roi": roi["all_schedule_button"],
            "threshold": 0.75,
            "action": "Click",
            "post_wait_freezes": 500,
            "timeout": 5000,
            "next": [wait_all, "[JumpBack]NavLoading"],
            "on_error": ["RecoverScheduleToMain"],
        }
        out[wait_all] = {
            "recognition": "TemplateMatch",
            "template": templates["all_schedule_title"],
            "roi": roi["all_schedule_title"],
            "threshold": 0.75,
            "timeout": 2000,
            "next": [run_region],
            "on_error": ["RecoverScheduleToMain"],
        }
        out[run_region] = {
            "next": ["ScheduleTicketsEmpty", gate],
        }

    for round_prefix, finish_node, candidate_kind, candidate_count in (
        (
            "FirstRound",
            "FinishScheduleFirstRoundRegion",
            "special",
            spec["special_candidate_count"],
        ),
        (
            "SecondRound",
            "FinishScheduleSecondRoundRegion",
            "heart",
            spec["heart_candidate_count"],
        ),
    ):
        for index in range(candidate_count):
            add_schedule_candidate(
                out,
                spec,
                round_prefix,
                candidate_kind,
                index,
                candidate_count,
                finish_node,
            )

    for round_prefix, finish, wait_closed, retry_close, decide in (
        (
            "FirstRound",
            "FinishScheduleFirstRoundRegion",
            "WaitScheduleFirstRoundAllScheduleClosed",
            "RetryCloseScheduleFirstRoundAllSchedule",
            "DecideScheduleFirstRoundRegion",
        ),
        (
            "SecondRound",
            "FinishScheduleSecondRoundRegion",
            "WaitScheduleSecondRoundAllScheduleClosed",
            "RetryCloseScheduleSecondRoundAllSchedule",
            "DecideScheduleSecondRoundRegion",
        ),
    ):
        out[finish] = {
            "recognition": "TemplateMatch",
            "template": templates["all_schedule_close"],
            "roi": roi["all_schedule_close"],
            "threshold": 0.75,
            "action": "Click",
            "post_wait_freezes": 300,
            "timeout": 2000,
            "next": [wait_closed],
            "on_error": [retry_close],
        }
        out[wait_closed] = {
            "recognition": "TemplateMatch",
            "template": templates["all_schedule_title"],
            "roi": roi["all_schedule_title"],
            "threshold": 0.75,
            "inverse": True,
            "next": [decide],
        }
        out[retry_close] = {
            "action": "Click",
            "target": [1138, 100],
            "post_wait_freezes": 300,
            "timeout": 2000,
            "next": [wait_closed],
            "on_error": ["RecoverScheduleToMain"],
        }

    out["DecideScheduleFirstRoundRegion"] = {
        "timeout": 1000,
        "next": [
            "ScheduleFirstRoundAtLastRegion",
            "AdvanceScheduleFirstRoundRegion",
            "RecoverScheduleToMain",
        ],
    }
    out["ScheduleFirstRoundAtLastRegion"] = {
        "recognition": "TemplateMatch",
        "template": templates["last_region_title"],
        "roi": roi["region_name"],
        "threshold": 0.75,
        "next": ["ReturnScheduleFirstRoundToHome"],
    }
    out["AdvanceScheduleFirstRoundRegion"] = {
        "recognition": "TemplateMatch",
        "template": templates["next_region_arrow"],
        "roi": roi["next_region_arrow"],
        "threshold": 0.75,
        "green_mask": True,
        "action": "Click",
        "max_hit": spec["max_region_hops"],
        "post_wait_freezes": 500,
        "next": ["OpenScheduleFirstRoundAllSchedule"],
        "on_error": ["RecoverScheduleToMain"],
    }
    out["ReturnScheduleFirstRoundToHome"] = {
        "recognition": "TemplateMatch",
        "template": "nav/back.png",
        "roi": [0, 0, 120, 100],
        "threshold": 0.7,
        "green_mask": True,
        "action": "Click",
        "post_wait_freezes": 500,
        "timeout": 5000,
        "next": ["WaitScheduleHomeForSecondRound", "[JumpBack]NavLoading"],
        "on_error": ["RecoverScheduleToMain"],
    }
    out["WaitScheduleHomeForSecondRound"] = {
        "recognition": "TemplateMatch",
        "template": templates["home_title"],
        "roi": roi["home_title"],
        "threshold": 0.75,
        "timeout": 3000,
        "next": ["ScheduleHomeTicketsEmpty", "OpenScheduleFirstRegionSecondRound"],
        "on_error": ["RecoverScheduleToMain"],
    }

    out["DecideScheduleSecondRoundRegion"] = {
        "timeout": 1000,
        "next": [
            "ScheduleSecondRoundAtLastRegion",
            "AdvanceScheduleSecondRoundRegion",
            "RecoverScheduleToMain",
        ],
    }
    out["ScheduleSecondRoundAtLastRegion"] = {
        "recognition": "TemplateMatch",
        "template": templates["last_region_title"],
        "roi": roi["region_name"],
        "threshold": 0.75,
        "next": ["NavReturnToMain"],
    }
    out["AdvanceScheduleSecondRoundRegion"] = {
        "recognition": "TemplateMatch",
        "template": templates["next_region_arrow"],
        "roi": roi["next_region_arrow"],
        "threshold": 0.75,
        "green_mask": True,
        "action": "Click",
        "max_hit": spec["max_region_hops"],
        "post_wait_freezes": 500,
        "next": ["OpenScheduleSecondRoundAllSchedule"],
        "on_error": ["RecoverScheduleToMain"],
    }

    out["CloseScheduleAllForNoTickets"] = {
        "recognition": "TemplateMatch",
        "template": templates["all_schedule_close"],
        "roi": roi["all_schedule_close"],
        "threshold": 0.75,
        "action": "Click",
        "post_wait_freezes": 300,
        "timeout": 2000,
        "next": ["WaitScheduleAllClosedForNoTickets"],
        "on_error": ["RetryCloseScheduleAllForNoTickets"],
    }
    out["WaitScheduleAllClosedForNoTickets"] = {
        "recognition": "TemplateMatch",
        "template": templates["all_schedule_title"],
        "roi": roi["all_schedule_title"],
        "threshold": 0.75,
        "inverse": True,
        "next": ["NavReturnToMain"],
    }
    out["RetryCloseScheduleAllForNoTickets"] = {
        "action": "Click",
        "target": [1138, 100],
        "post_wait_freezes": 300,
        "timeout": 2000,
        "next": ["WaitScheduleAllClosedForNoTickets"],
        "on_error": ["RecoverScheduleToMain"],
    }
    out["RecoverScheduleToMain"] = {"next": ["NavReturnToMain"]}
    return out


def sweep_stage_option(spec: dict[str, Any], category: dict[str, Any]) -> dict[str, Any]:
    target = node_name(category, "Find", f"{spec['flow_suffix']}StageNumber")
    return {
        "type": "select",
        "default_case": str(spec["default_stage"]),
        "cases": [
            {
                "name": str(stage),
                "pipeline_override": {target: {"expected": f"^{stage:02d}$"}},
            }
            for stage in range(1, spec["stage_count"] + 1)
        ],
    }


def sweep_count_option(spec: dict[str, Any], category: dict[str, Any]) -> dict[str, Any]:
    run = node_name(category, "Run", spec["flow_suffix"])
    add = node_name(category, "Add", "SweepCount")
    cases = []
    for count in range(7):
        add_override: dict[str, Any] = {"enabled": count >= 2}
        if count >= 2:
            add_override["repeat"] = count - 1
        cases.append(
            {
                "name": str(count),
                "label": f"{count} 次",
                "pipeline_override": {
                    run: {"enabled": count > 0},
                    add: add_override,
                },
            }
        )
    return {"type": "select", "default_case": "0", "cases": cases}


def shop_items_option(category: dict[str, Any]) -> dict[str, Any]:
    prefix = category["prefix"]
    cases = []
    for row in range(1, category["rows"] + 1):
        page = (row - 1) // 2 + 1
        for column in range(1, category["columns"] + 1):
            cases.append(
                {
                    "name": f"{row}-{column}",
                    "pipeline_override": {
                        f"Run{prefix}ShopPurchase": {"enabled": True},
                        f"Click{prefix}ShopItemR{row}C{column}": {"enabled": True},
                        f"Purchase{prefix}ShopPage{page}": {"enabled": True},
                    },
                }
            )
    return {"type": "checkbox", "default_case": [], "cases": cases}


def generate_interface(spec: dict[str, Any]) -> OrderedDict[str, Any]:
    base = spec["interface"]
    out: OrderedDict[str, Any] = OrderedDict()
    for key in (
        "interface_version",
        "name",
        "description",
        "contact",
        "license",
        "welcome",
        "github",
        "version",
        "controller",
        "resource",
    ):
        out[key] = base[key]

    tasks = []
    for sweep in spec["sweeps"]:
        options = []
        for category in sweep["categories"]:
            options.extend([f"{category['label']}关号", f"{category['label']}扫荡次数"])
        tasks.append({"name": sweep["task_name"], "entry": sweep["entry"], "option": options})
    tasks.append({"name": spec["shop"]["task_name"], "entry": spec["shop"]["entry"], "option": ["商店购买栏目"]})
    tasks.extend(base["static_tasks"])
    out["task"] = tasks

    options: OrderedDict[str, Any] = OrderedDict()
    cafe = base["cafe_option"]
    options["咖啡厅功能"] = {
        "type": cafe["type"],
        "default_case": cafe["default_case"],
        "cases": [
            {
                "name": case["name"],
                "pipeline_override": {
                    "RunCafe1HeadPat": {"enabled": case["headpat"]},
                    "RunCafeIncomeClaim": {"enabled": case["income"]},
                    "RunCafe2HeadPatPlan": {"enabled": case["cafe2"]},
                },
            }
            for case in cafe["cases"]
        ],
    }
    for sweep in spec["sweeps"]:
        for category in sweep["categories"]:
            options[f"{category['label']}关号"] = sweep_stage_option(sweep, category)
            options[f"{category['label']}扫荡次数"] = sweep_count_option(sweep, category)
    options["商店购买栏目"] = {
        "type": "checkbox",
        "default_case": [],
        "cases": [
            {"name": category["label"], "option": [category["option_name"]]}
            for category in spec["shop"]["categories"]
        ],
    }
    for category in spec["shop"]["categories"]:
        options[category["option_name"]] = shop_items_option(category)
    out["option"] = options
    return out


def render(value: Any) -> str:
    return GENERATED_HEADER + json.dumps(value, ensure_ascii=False, indent=2) + "\n"


def generated_files(spec: dict[str, Any]) -> dict[Path, str]:
    files = {
        ROOT / sweep["output"]: render(generate_sweep(sweep))
        for sweep in spec["sweeps"]
    }
    files[ROOT / spec["shop"]["output"]] = render(generate_shop(spec["shop"]))
    files[ROOT / spec["schedule"]["output"]] = render(generate_schedule(spec["schedule"]))
    files[ROOT / "assets" / "interface.json"] = render(generate_interface(spec))
    return files


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="update generated resources")
    mode.add_argument("--check", action="store_true", help="fail when generated resources are stale")
    args = parser.parse_args()

    spec = json.loads(SPEC_PATH.read_text(encoding="utf-8"))
    files = generated_files(spec)
    stale = []
    for path, content in files.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
            print(f"updated {path.relative_to(ROOT)}")
        else:
            stale.append(path.relative_to(ROOT))

    if stale:
        print("Generated resources are stale:", file=sys.stderr)
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        print("Run: python tools/generate_resources.py --write", file=sys.stderr)
        return 1
    if not args.write:
        print("Generated resources are up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
