name: check

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/check.yml"
      - "assets/**"
      - "deps/tools/*.schema.json"
      - "docs/**"
      - "tools/**"
      - "README.md"
      - "maatools.config.mts"
      - "package.json"
      - "package-lock.json"
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/check.yml"
      - "assets/**"
      - "deps/tools/*.schema.json"
      - "docs/**"
      - "tools/**"
      - "README.md"
      - "maatools.config.mts"
      - "package.json"
      - "package-lock.json"
  workflow_dispatch:

jobs:
  resource:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Node dependencies
        run: npm ci

      - name: Run maa-tools checker
        run: npx @nekosu/maa-tools check

      - name: Check generated resources
        run: python tools/generate_resources.py --check

      - name: Check Pipeline graph
        run: python tools/check_pipeline.py

      - name: Validate JSON Schema
        run: |
          python -m pip install jsonschema==4.26.0 referencing==0.37.0
          python tools/validate_schema.py --schema-dir deps/tools --resource-dirs assets/resource --interface-files assets/interface.json assets/interface.check.json

      - name: Check documentation
        run: python tools/check_docs.py
